version: 2

updates:
  # Updates versions for GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "chore(deps):"

  # Updates versions for npm dependencies
  - package-ecosystem: "npm"
    directory: "/infra"
    schedule:
      interval: "weekly"
      time: "08:00"
      timezone: "America/Chicago"
    commit-message:
      prefix: "chore(deps):"